# Generated by Django 4.0.4 on 2022-09-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_end',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='time_start',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
