# Generated by Django 3.2.16 on 2022-10-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221011_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='time_end',
        ),
    ]
