# Generated by Django 3.2.16 on 2022-10-13 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_time_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='time_end_hour',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='time_end_minute',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='time_start_hour',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='time_start_minute',
        ),
        migrations.AddField(
            model_name='profile',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
