# Generated by Django 3.2.16 on 2022-10-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20221013_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='end_time',
            field=models.TimeField(default='18:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='start_time',
            field=models.TimeField(default='8:00:00', null=True),
        ),
    ]
