# Generated by Django 3.2.16 on 2022-10-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20221013_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='remember_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='token',
            field=models.JSONField(null=True),
        ),
    ]
