# Generated by Django 3.2.16 on 2022-10-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20221013_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
