# Generated by Django 3.2.16 on 2022-11-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20221108_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='remember_me',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
