# Generated by Django 4.0.4 on 2022-09-12 01:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=100)),
                ('meeting_description', models.TextField(blank=True)),
                ('meeting_deadline', models.DateField(default=datetime.date.today)),
                ('meeting_duration_hours', models.IntegerField()),
                ('meeting_duration_minutes', models.IntegerField()),
                ('meeting_link_location', models.CharField(blank=True, max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingImmediate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=100)),
                ('meeting_id', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='PendingAttendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('meeting_creator_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MeetingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=100)),
                ('weekday', models.CharField(max_length=100)),
                ('time_hours', models.CharField(max_length=100)),
                ('time_minutes', models.CharField(max_length=100)),
                ('am_or_pm', models.CharField(max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start', models.IntegerField(default=800)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_scheduler.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_owner', models.CharField(max_length=100)),
                ('event_start', models.CharField(max_length=100)),
                ('event_end', models.CharField(max_length=100)),
                ('event_number_of_people', models.IntegerField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_scheduler.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict', models.CharField(max_length=100)),
                ('meeting_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smart_scheduler.meetingtime')),
            ],
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee_name', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('rsvp_status', models.CharField(max_length=100)),
                ('meeting_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_scheduler.meeting')),
            ],
        ),
    ]
