# Generated by Django 4.0.4 on 2022-09-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conflict',
            old_name='conflict',
            new_name='name',
        ),
    ]
