# Generated by Django 4.0.4 on 2022-09-21 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0002_rename_conflict_conflict_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='conflict',
            name='meeting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='smart_scheduler.meeting'),
        ),
    ]
