# Generated by Django 3.2.15 on 2022-09-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0003_conflict_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_tz',
            field=models.CharField(default='America/Chicago', max_length=100),
        ),
    ]
