# Generated by Django 4.0.4 on 2022-09-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0004_event_event_tz'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pendingattendee',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
