# Generated by Django 3.2.16 on 2022-10-12 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_scheduler', '0006_remove_event_event_tz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start_hour', models.IntegerField(null=True)),
                ('time_start_minute', models.IntegerField(null=True)),
                ('time_end_hour', models.IntegerField(null=True)),
                ('time_end_minute', models.IntegerField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
