# Generated by Django 3.2.16 on 2022-10-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0007_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
