# Generated by Django 3.2.16 on 2022-11-08 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0008_delete_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_start',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
