# Generated by Django 3.2.16 on 2022-11-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0009_meeting_meeting_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='remember_me',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='token',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
