# Generated by Django 3.2.16 on 2022-11-13 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0010_auto_20221113_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='contact_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_scheduler.contact'),
        ),
    ]
