# Generated by Django 3.2.16 on 2022-11-15 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0011_attendee_contact_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='contact_name',
        ),
    ]
