# Generated by Django 3.2.16 on 2022-11-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_scheduler', '0012_remove_attendee_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
