# Generated by Django 3.2.16 on 2022-11-28 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smart_scheduler', '0013_alter_contact_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('contact_name', 'author')},
        ),
    ]
