branch-defaults:
  Hosting:
    environment: smart-scheduler
    group_suffix: null
  main:
    environment: django-environment
    group_suffix: null
environment-defaults:
  django-env:
    branch: null
    repository: null
  smart-scheduler-env:
    branch: null
    repository: null
  smart-scheduler-ver2:
    branch: null
    repository: null
global:
  application_name: smart-scheduler
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
