# Generated by Django 3.2.16 on 2023-07-07 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, help_text='Author Name', max_length=25)),
                ('Org', models.CharField(blank=True, help_text='Organization Name', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Recipe Name', max_length=20)),
                ('Ingredients', models.JSONField(help_text='Recipe Ingredients')),
                ('Directions', models.JSONField(help_text='Recipe Directions')),
                ('img', models.ImageField(help_text='Recipe Image', upload_to='images/')),
                ('mealtype', models.CharField(blank=True, choices=[('e', 'Entree'), ('b', 'Bread'), ('s', 'Snack'), ('d', 'Drink'), ('t', 'Dessert')], help_text='Type of Meal: entree, snack, bread, drink', max_length=1)),
                ('Author', models.ForeignKey(blank=True, help_text='Recipe Author', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recipebookapp.recipeauthor')),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
    ]
