# Generated by Django 3.2.16 on 2023-07-06 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipebookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='Author',
            field=models.OneToOneField(blank=True, help_text='Recipe Author', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='recipebookapp.recipeauthor'),
        ),
        migrations.AlterField(
            model_name='recipemodel',
            name='Directions',
            field=models.JSONField(help_text='Recipe Directions'),
        ),
    ]
