# Generated by Django 3.2.16 on 2023-07-09 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipebookapp', '0002_recipemodel_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipemodel',
            name='Users',
        ),
    ]
