# Generated by Django 4.2.2 on 2023-08-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebookapp', '0003_remove_recipemodel_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipemodel',
            name='Directions',
            field=models.CharField(help_text='Recipe Directions', max_length=999),
        ),
    ]
